/** Server workflow budgets and the browser allowance derived from them. */
export const RAG_RETRIEVAL_EXECUTION_BUDGET_MS = 30_000;
export const RAG_GENERATION_EXECUTION_BUDGET_MS = 30_000;
export const RAG_AGENTIC_EXECUTION_BUDGET_MS = 45_000;
export const RAG_CLIENT_NETWORK_ALLOWANCE_MS = 15_000;

export const RAG_CLIENT_REQUEST_TIMEOUT_MS = Math.max(
  RAG_RETRIEVAL_EXECUTION_BUDGET_MS + RAG_GENERATION_EXECUTION_BUDGET_MS,
  RAG_AGENTIC_EXECUTION_BUDGET_MS
) + RAG_CLIENT_NETWORK_ALLOWANCE_MS;

